<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

/**
 * One buyer's rating + comment on one listing.
 *
 * The custom-PK conventions are the project's, not a quirk: LRV_ID is a
 * CHAR(6) uppercase string generated by the Str::random(6) uniqueness loop,
 * the timestamps are custom-named and have to be written by hand because
 * $timestamps is off, and the one-review-per-user rule is a UNIQUE key on
 * (LST_ID, USR_ID) rather than something enforced in the controller.
 *
 * HIDDEN is a moderation verdict, not a delete. Hiding removes the review
 * from the visible list and from the rating average, and it can be undone;
 * nothing here is ever hard-deleted by an admin.
 */
class ListingReview extends Model
{
    protected $table = 'listing_review';

    protected $primaryKey = 'LRV_ID';

    public $incrementing = false;

    protected $keyType = 'string';

    public $timestamps = false;

    protected $guarded = [];

    public const STATUS_VISIBLE = 'VISIBLE';

    public const STATUS_HIDDEN = 'HIDDEN';

    /**
     * The reviewer. Deliberately a direct link to `user` rather than to buyer:
     * a review only needs the reviewer's name, and going through buyer ->
     * user would exclude a reviewer whose buyer row is missing for any reason.
     */
    public function user()
    {
        return $this->belongsTo(User::class, 'USR_ID', 'USR_ID');
    }

    public function listing()
    {
        return $this->belongsTo(Listing::class, 'LST_ID', 'LST_ID');
    }

    /**
     * Only the reviews a buyer is allowed to see.
     *
     * Every read path goes through this rather than filtering in PHP, so a
     * hidden review cannot leak through a forgotten where() and the rating
     * average cannot disagree with the list above it.
     */
    public function scopeVisible(Builder $query): Builder
    {
        return $query->where('LRV_STATUS', self::STATUS_VISIBLE);
    }

    public function isHidden(): bool
    {
        return $this->LRV_STATUS === self::STATUS_HIDDEN;
    }

    /**
     * A free next ID in the project's CHAR(6) style.
     *
     * The do/while existence check is the codebase's convention, kept here so
     * a controller can call newId() instead of repeating the loop (Report does
     * exactly this).
     */
    public static function newId(): string
    {
        do {
            $id = strtoupper(Str::random(6));
        } while (self::where('LRV_ID', $id)->exists());

        return $id;
    }
}